### ISSUE TITLE
Use release phase instead

### ISSUE THREAD

**Issue by schneems** [gunpowderlabs/buildpack-ruby-rake-deploy-tasks#14]
Can we recommend people use release phase in the readme? https://devcenter.heroku.com/articles/release-phase

**Comment by azolotov** [comment]
@schneems Yes. Want to send a PR?

**Comment by taylorzr** [comment]
Seems like there are a few problems here:
  - [Heroku says](https://devcenter.heroku.com/articles/buildpack-api#side-effects):
    > Buildpack developers should avoid generating side effects during the build. For example, it is not recommended to perform database migrations in the compile script.
  - But the release phase is still in beta

I don't think it makes sense to deprecate this gem entirely until the release phase is out of beta.

**Comment by azolotov** [comment]
@schneems I think @taylorzr is right. We shouldn't deprecate this until it's out of beta, and supports side effects like running DB migrations.

I [added a note](https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks/commit/132e8ea0bdf179dac3dfd06e12ed658e0e68a24a) to the readme linking to Release Phase.

**Comment by schneems** [comment]
DB migrate works just fine. That's what I use it for.

There are reasons to not do this at scale though, for example if you accidentally lock a HUGE table there is no way to stop or cancel the release phase. That's why we don't officially recommend using it for DB migrate. In practice it's what most smaller and medium apps I've seen use it for.
