### ISSUE TITLE
Fetching set buildpack 

### ISSUE THREAD

**Issue by thewesker** [gunpowderlabs/buildpack-ruby-rake-deploy-tasks#8]
Used your instructions exactly, Ruby buildpack works and then this:

-----> Fetching set buildpack https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks... done
 !     Push rejected, failed to detect set buildpack https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks

**Comment by wrozka** [comment]
Does your project include a `Rakefile`? `buildpack-ruby-rake-depoly-tasks` requires it in the [detect script](https://github.com/gunpowderlabs/buildpack-ruby-rake-deploy-tasks/blob/master/bin/detect).

**Comment by wrozka** [comment]
I'm closing this issue, but feel free to reopen it anytime if you have any problems.
